# Generated by Django 4.2.1 on 2023-11-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='price',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='items',
            name='weight',
            field=models.CharField(default='', max_length=100),
        ),
    ]
