# Generated by Django 4.2.1 on 2023-12-13 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_category_alter_items_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='women.category'),
        ),
    ]
