# Generated by Django 4.2.1 on 2023-12-13 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0004_items_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Товары', 'verbose_name_plural': 'Товары'},
        ),
    ]
